version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5009:5009"
    environment:
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5009"
